import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AddHeader from "@/components/Header";
import AddFooter from "@/components/Footer";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="de">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
            >
                <div className="min-h-screen flex flex-col">
                    <header className="fixed bg-brand/10 dark:bg-brand/20 top-0 w-full shadow-sm z-50">
                        <div className="mx-auto max-w-4xl px-4 py-3 flex items-center justify-center">
                            <AddHeader />
                        </div>
                    </header>

                    <main className="flex-1 pt-24 mx-auto max-w-4xl px-4">
                        {children}
                    </main>

                    <footer className="w-full bg-brand/10 dark:bg-brand/20 shadow-sm mt-auto">
                        <div className="mx-auto max-w-4xl px-4 py-3 text-m text-gray-500 flex items-center justify-center space-x-2">
                            <span>
                                Pflegehinweise beispielsweise hier erhalten:
                            </span>
                            <AddFooter />
                        </div>
                    </footer>
                </div>
            </body>
        </html>
    );
}
